-- Generated from songs.json
insert into public.songs (id, title_ja, title_en, video_id, answers_normalized) values
  ('idol', 'アイドル', 'Idol', 'ZRtdQ81jPUQ', array['アイドル']::text[]),
  ('yoru-ni-kakeru', '夜に駆ける', 'Into the Night', 'by4SYYWlhEs', array['夜に駆ける']::text[]),
  ('gunjou', '群青', 'Blue', 'Y4nEEZwckuU', array['群青']::text[]),
  ('kaibutsu', '怪物', 'Monster', 'dy90tA3TT1c', array['怪物']::text[]),
  ('harujion', 'ハルジオン', 'Halzion', 'kzdJkT4kp-A', array['ハルジオン']::text[]),
  ('sangenshoku', '三原色', 'RGB', 'nhOhFOoURnE', array['三原色']::text[]),
  ('yuusya', '勇者', 'The Brave', 'OIBODIPC_8Y', array['勇者']::text[]),
  ('shukufuku', '祝福', 'The Blessing', '3eytpBOkOFA', array['祝福']::text[]),
  ('tabun', 'たぶん', 'Probably', '8iuLXODzL04', array['たぶん']::text[]),
  ('anoyumewonazotte', 'あの夢をなぞって', 'Tracing A Dream', 'sAuEeM_6zpk', array['あの夢をなぞって']::text[]),
  ('haruka', 'ハルカ', 'Haruka', 'vd3IlOjSUGQ', array['ハルカ']::text[]),
  ('encore', 'アンコール', 'Encore', 'vcGbefQBvJ4', array['アンコール']::text[]),
  ('loveletter', 'ラブレター', 'Love Letter', 'mnta9Pp2LqA', array['ラブレター']::text[]),
  ('yasashiisuisei', '優しい彗星', 'Comet', 'VyvhvlYvRnc', array['優しい彗星']::text[]),
  ('seventeen', 'セブンティーン', 'Seventeen', '0yoM7ETNPIY', array['セブンティーン']::text[]),
  ('biribiri', 'Biri-Biri', 'Biri-Biri', 'shZyg5VFI1Y', array['biribiri']::text[]),
  ('adventure', 'アドベンチャー', 'Adventure', 'Av3xaZkVpJs', array['アドベンチャー']::text[]),
  ('tsubame', 'ツバメ', 'The Swallow', 'qDL3zhB8-MM', array['ツバメ']::text[]),
  ('mousukoshidake', 'もう少しだけ', 'Just a Little Step', 'K1Tz2yNmamI', array['もう少しだけ']::text[]),
  ('moshimoinochigaegaketara', 'もしも命が描けたら', 'If I Could Draw Life', 'I0kytvnHG-Q', array['もしも命が描けたら']::text[]),
  ('taisyouroman', '大正浪漫', 'Romance', 'wJQ9ig_d8yY', array['大正浪漫']::text[]),
  ('uminomanimani', '海のまにまに', 'manimani', '7G0ovtPqHnI', array['海のまにまに']::text[]),
  ('watchme', 'Watch me!', 'Watch me!', 'evtoG-4dLM4', array['watchme']::text[]),
  ('sukida', '好きだ', 'Loving You', 'WQ6ePunO8uY', array['好きだ']::text[]),
  ('butainitatte', '舞台に立って', 'On the Stage', 'GWDzKel_vuQ', array['舞台に立って']::text[]),
  ('heartbeat', 'HEART BEAT', 'HEART BEAT', 'ZSr3P-Rn6x0', array['heartbeat']::text[]),
  ('gekijou', '劇上', 'Gekijou', 'GuIkxXiVHps', array['劇上']::text[]),
  ('monotone', 'モノトーン', 'Monotone', 'sJ-2X3rHtXw', array['モノトーン']::text[]),
  ('players', 'PLAYERS', 'PLAYERS', 'ZfR_FP_7w00', array['players']::text[]),
  ('baby', 'BABY', 'BABY', 'tWqZxTAy7rU', array['baby']::text[]),
  ('adorena', 'アドレナ', 'Adorena', 'ARqP5ohiubY', array['アドレナ']::text[]),
  ('undead', 'UNDEAD', 'UNDEAD', 'Jj1_mfUzjOs', array['undead']::text[]),
  ('newme', 'New me', 'New me', 'HRlW6yZo6Kc', array['newme']::text[]),
  ('mister', 'ミスター', 'Mister', '2-c0DFt6vK4', array['ミスター']::text[])
on conflict (id) do update set
  title_ja = excluded.title_ja,
  title_en = excluded.title_en,
  video_id = excluded.video_id,
  answers_normalized = excluded.answers_normalized;

